### ISSUE TITLE
Not showing pokemon as expected

### ISSUE THREAD

**Issue by siideffect** [istornz/iPokeGo#135]
Hello, first of all, thanks for sharing this awesome client. 
Now, lets talk about the problem. After pokemon app update, i migrated from heroku to jelastic(deployed using button on github page), and installed the new client version on my simulator/personal device.
But i noticed the app is not working accurately as before, i make an example: i had a pokemon near my position(blue placeholder), but it wasnt displayed by ipokego. I had pokemon go app and it appeared, so it definitely didn t show the spawn location. All the pokemon spawns i had with previous version, are now disappeared, i can see them in pokemon go app but not on ipokego. 
Also, the green placeholder i can set on map, is not working as expected( the pokemon appears around it, in a long range, i have a ss which shows a perfect(almost) circle of pokemons around it).

What is causing this? i had a strange warning on xcode before compiling project, about a loss of precision, here the warning log

 Implicit conversion loses integer precision: 'long _Nullable' to 'int32_t' (aka 'int')

There are exactly 3 warnings like this, but i dont know if this could be related to the issue i am having.
So, definitely, why are the pokemon not showing properly? server side problem or client side?
Thanks for the attention

**Comment by markvl91** [comment]
If you're running the current master branch of the server on Jelastic, it's probably because Niantic updated their own servers, which causes loss of pokemon in the area of 70m to 100m from the scan cell. You should probably update the server to run the development branch.

**Comment by siideffect** [comment]
Yes i deployed master branch directly using button for jelastic. You think i can solve updating the server with develop branch?

**Comment by SrGMC** [comment]
@siideffect Yes and no. The development branch works, but Niantic has banned all major VPS such as AWS, Jellastic or Heroku. So the only way to make it work is hosting your map on your own server or using a less common VPS service (that doesn't use AWS).

**Comment by siideffect** [comment]
@SrGMC well since i am an ios developer, i am not very good on the server-side. Could you suggest some parameter or service, tutorial, that could help me solve this ?

**Comment by Bizadon** [comment]
@markvl91 sorry for the stupid question, what do you mean about "development branch"? what is it? I have the same problem, what should I update on the server? Have the server on DigitalOcean

**Comment by siideffect** [comment]
@Bizadon you need to update server by going on github page and switch to development(download new version). Then you need to deploy that development version. Then, we need to find any server where to deploy the project which is not blocked by niantic

**Comment by SrGMC** [comment]
@siideffect There's a pretty good tutorial at the [PokémonGo-Map Wiki](https://jonaharagon.github.io/PoGoMapWiki/#!index.md) on how to setup a local server on your computer (Windows, Linux or Mac OS).

For the VPS side, I don't know any good server that is not blocked by Niantic. Maybe a search on Google might throw some of them, but be sure they are trustworthy.

I'm currently running a Pokemon Map server on a Raspberry Pi at my home and using the iPokeGo App and it's working pretty well

**Comment by SrGMC** [comment]
@Bizadon Some people are saying that some DigitalOcean IP's are not blocked (It seems that DO doesn't publish there IP range).
Also, some people suggest on [/r/pokemongodev](http://reddit.com/r/pokemongodev) to make a new droplet either in the same location or in another one. (NYC1 seems to not work but NYC2 does)

**Comment by siideffect** [comment]
@SrGMC i followed tutorial, the server is running without problems using a google maps api key generated for ios device, and with some problem with browser key. 
Once the server is running(with browser key), what is the address i should use on the ios client? http://127.0.0.1:5000 or my local ip address(followed by port) ?

**Comment by DmitryMironenko** [comment]
Reproduced  for me. Trying development, master, v2.1.0 and v2.0 branches of server. Server hosted on my home PC with ngrok. IPokeGo successfully started, but not one pokemon not displayed on the map. Used iPokeGo2_current_version.ipa. PokemonGo-Map correctly work from browser.

**Comment by DmitryMironenko** [comment]
Fixed. Solution was found in https://github.com/istornz/iPokeGo/issues/148

**Comment by siideffect** [comment]
excuse me @DmitryMironenko , yes i solved using ngrok,actually i am running all on localhost.
Whats the difference using the ipa vs using the source code? I am still experience lossing of pokemon around me(with placeholder setted by me it s working greatly), because i can see pokemon in pokemon go, but not in localhost. Is there a difference?

**Comment by DmitryMironenko** [comment]
Use latest v2.0.1 of iPokeGo. In source code still old version.

**Comment by SrGMC** [comment]
@siideffect Use the local IP of your machine, followed by the port, and make sure in the command to start the server has "-H 0.0.0.0 -P 5000" attached to it.
If you are using ngrok, I haven't used it yet, so I can't tell you how it works

**Comment by siideffect** [comment]
so it s a client side problem... i think i m gonna wait for the source code and compile it myself when it will be released(i have not jailbreak). Thank you all very much

**Comment by jerry317** [comment]
I can't see any pokemon with the latest code today.

**Comment by istornz** [comment]
@jerry317 What is your server version ? (Master or Dev branch)

**Comment by siideffect** [comment]
@istornz hello dimitry, will you release the source code instead of the ipa?

**Comment by Bart274** [comment]
The latest release 2.0.2 isn't working for me either, my pokemongo server is the latest dev version, but I don't get any result

**Comment by istornz** [comment]
I close this issue, please open an another one if the problem persists
